/**
 * THE SCARLET THREAD — Story Data
 * Eight Old Testament chapters tracing the thread of redemption
 * from Creation to the Messianic prophecies.
 *
 * Theological framework: Seventh-day Adventist, Christ-centered,
 * Great Controversy lens, sanctuary as the unifying motif.
 */

const stories = [
  {
    id: 'creation',
    chapter: 1,
    title: 'Creation',
    subtitle: 'The Character of the Creator',
    scripture: '"In the beginning God created the heavens and the earth. And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters. And God said, Let there be light: and there was light."',
    scriptureRef: 'Genesis 1:1–3 (KJV)',
    narrative: 'The opening words of Scripture are not merely an account of origins. They are a revelation of character. The God who speaks light into darkness, who fills emptiness with life, who shapes beauty out of nothing, is declaring something about Himself before He ever declares a law. He is generous. He is creative. He is relational. When He forms humanity in His own image, it is not to gain servants but to share fellowship. And when He rests on the seventh day, the Sabbath, He is not recovering from effort. He is pausing to be present with the ones He made. That rest is still an invitation.',
    jesusConnection: 'The Gospel of John opens with the same phrase: "In the beginning." It reveals that Jesus, the Word, was the active agent of creation. "All things were made by him; and without him was not any thing made that was made" (John 1:3). The Creator would one day enter His own creation, not as a king, but as an infant in a borrowed manger.',
    jesusLabel: 'The Word Who Made All Things',
    color: '#2a8a9e',
    accentColor: '#d4a843',
  },
  {
    id: 'the-fall',
    chapter: 2,
    title: 'The Fall & The Promise',
    subtitle: 'Where the Conflict Began',
    scripture: '"And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel."',
    scriptureRef: 'Genesis 3:15 (KJV)',
    narrative: 'The conflict did not begin in a garden. It began in heaven, when a created being questioned whether God\'s government was truly just. That accusation travelled to earth in the form of a question: "Has God really said?" It was not a challenge to a rule. It was a challenge to God\'s character. And humanity chose to believe the accusation. Sin entered, and with it came separation, sorrow, and death. But even in that moment of fracture, God responded not with destruction but with a promise. A Seed would come, born of a woman, who would crush the serpent\'s power. The wound would be real, but the outcome was already certain.',
    jesusConnection: 'Theologians call this the Protoevangelium, the first gospel. The "Seed of the woman" is Christ Himself. He would be wounded at Calvary, bruised in His heel, but through that suffering He would destroy the one who held the power of death. The first prophecy in Scripture is a promise of rescue, spoken while the dust of Eden was still fresh.',
    jesusLabel: 'The Promised Seed',
    color: '#8b6914',
    accentColor: '#d4a843',
  },
  {
    id: 'noah',
    chapter: 3,
    title: 'Noah & The Flood',
    subtitle: 'One Door, One Invitation',
    scripture: '"And the Lord said unto Noah, Come thou and all thy house into the ark; for thee have I seen righteous before me in this generation."',
    scriptureRef: 'Genesis 7:1 (KJV)',
    narrative: 'The world before the flood had reached a point where violence and corruption had become the norm. Yet in the middle of that generation, one man chose to walk faithfully with God. For 120 years, Noah built an enormous vessel and preached righteousness to a world that had never seen rain. He was mocked for his trust. And then God said, "Come." Not "go into the ark," but come. God was already inside. After every creature and every willing soul had entered, the Lord Himself closed the door. The rain fell, the waters rose, and only those inside were safe. When it was over, God set a rainbow in the sky, a covenant sign that mercy outlasts judgment.',
    jesusConnection: 'The ark had one door, and God Himself sealed it. Centuries later, Jesus would say, "I am the door: by me if any man enter in, he shall be saved" (John 10:9). Peter draws a direct line from the flood to salvation through Christ: just as the ark carried Noah\'s family through the water, so baptism and faith in Christ carry believers through judgment (1 Peter 3:20–21). The invitation is the same. Come.',
    jesusLabel: 'The Door of Salvation',
    color: '#1a6b6b',
    accentColor: '#4ecdc4',
  },
  {
    id: 'abraham',
    chapter: 4,
    title: 'Abraham\'s Sacrifice',
    subtitle: 'The Lord Will Provide',
    scripture: '"And Abraham said, My son, God will provide himself a lamb for a burnt offering."',
    scriptureRef: 'Genesis 22:8 (KJV)',
    narrative: 'God asked Abraham to do something unthinkable: to offer his son, the child of promise, the one through whom all the covenant blessings were supposed to flow. Abraham did not understand the reason, but he had spent decades learning that God does not break His word. So he obeyed. He built the altar, laid the wood, bound the boy, and raised the knife. At that moment God intervened. A ram caught in a thicket became the substitute sacrifice. Abraham named that place Yahweh Yireh: "The Lord Will Provide." That mountain, Moriah, would one day become the site of Solomon\'s temple and the region where the true Lamb would be offered.',
    jesusConnection: 'On that same mountain range, centuries later, God would not stay His hand. He would offer His own Son as the sacrifice Abraham was spared from making. "For God so loved the world, that he gave his only begotten Son" (John 3:16). Abraham spoke more truly than he knew when he said God would provide Himself a lamb. The ram in the thicket was a shadow. The Lamb of God was the substance.',
    jesusLabel: 'The Lamb God Provided',
    color: '#1a3a5c',
    accentColor: '#d4a843',
  },
  {
    id: 'exodus',
    chapter: 5,
    title: 'The Exodus & Passover',
    subtitle: 'Blood on the Doorpost',
    scripture: '"For even Christ our passover is sacrificed for us."',
    scriptureRef: '1 Corinthians 5:7 (KJV)',
    narrative: 'For four centuries, God\'s people lived under the weight of Egyptian bondage. When the time came for their deliverance, God did not act quietly. Each of the ten plagues was a public judgment against the gods of Egypt, a demonstration before the watching world that the God of Israel is the true and living God. The final plague required a response from His people: a spotless lamb, its blood applied to the doorposts, and a meal eaten in readiness to leave. That night, the angel of death passed over every blood-marked home. The firstborn inside were safe. Israel walked out of slavery, and when the sea stood between them and freedom, God opened a path through the water itself.',
    jesusConnection: 'Paul states it plainly: "Christ our Passover is sacrificed for us." The spotless lamb, the applied blood, the deliverance from bondage, the passage through the water, every element of the Exodus finds its fulfillment in Christ. His blood, given freely at Calvary, is the reason death passes over those who trust in Him. And like Israel, believers are called to walk forward into freedom, even when the path seems impossible.',
    jesusLabel: 'Our Passover Lamb',
    color: '#c47a2a',
    accentColor: '#8b2635',
  },
  {
    id: 'sanctuary',
    chapter: 6,
    title: 'The Sanctuary',
    subtitle: 'The Gospel in Miniature',
    scripture: '"And let them make me a sanctuary; that I may dwell among them."',
    scriptureRef: 'Exodus 25:8 (KJV)',
    narrative: 'When God gave Moses the design for the sanctuary, He was doing more than prescribing a place of worship. He was laying out the entire plan of salvation in physical form. The altar of burnt offering at the entrance spoke of the cost of sin and the gift of substitution. The laver spoke of cleansing. Inside, the bread of the Presence pointed to daily sustenance from God, the lampstand to His guiding light, and the altar of incense to the prayers of His people rising before His throne. Behind the inner veil, in the Most Holy Place, the Ark of the Covenant held the law of God beneath the mercy seat, justice and grace resting together. Once each year on the Day of Atonement, the high priest entered that innermost room to cleanse the sanctuary of the accumulated record of sin. It was the most solemn day in Israel\'s calendar, and it pointed forward to a work still unfolding.',
    jesusConnection: 'The book of Hebrews calls the earthly sanctuary "a shadow of heavenly things" (Hebrews 8:5). Jesus is the Lamb sacrificed at the altar, the Bread of Life, the Light of the World, and our great High Priest who "ever liveth to make intercession for us" (Hebrews 7:25). When the veil of the temple tore at His crucifixion (Matthew 27:51), it signalled that the way into God\'s presence was now open to all who believe. The sanctuary is not a relic. It is a living map of what Christ has done, is doing, and will complete.',
    jesusLabel: 'Our Great High Priest',
    color: '#4a2d6b',
    accentColor: '#d4a843',
  },
  {
    id: 'david',
    chapter: 7,
    title: 'David\'s Kingdom',
    subtitle: 'A Throne Built on Promise',
    scripture: '"I am the root and the offspring of David, and the bright and morning star."',
    scriptureRef: 'Revelation 22:16 (KJV)',
    narrative: 'David was the youngest son, overlooked by his family and unknown to his nation. Yet God saw in this shepherd boy a heart that sought Him. David defeated the giant, united a fractured kingdom, and established Jerusalem as the city of God. He was also deeply flawed, a man who knew failure and repentance in equal measure. What set David apart was not his perfection but his willingness to return. God made David an extraordinary covenant: his throne would endure forever. That promise did not rest on David\'s character. It rested on God\'s faithfulness. The kingdom David built was temporary, but the King who would come from his line would reign without end.',
    jesusConnection: 'Throughout the Gospels, Jesus is called "the Son of David." He was born in David\'s city, Bethlehem, from David\'s lineage, in direct fulfilment of the ancient promise. But unlike David, Jesus is the sinless King. He did not come to claim an earthly throne. He came as a servant, born in a manger, crowned with thorns, and raised to life so that His kingdom, one built on justice and mercy rather than power, would have no end.',
    jesusLabel: 'Son of David, Eternal King',
    color: '#1a3a5c',
    accentColor: '#d4a843',
  },
  {
    id: 'prophecy',
    chapter: 8,
    title: 'Prophetic Voices',
    subtitle: 'Written Centuries Before',
    scripture: '"But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."',
    scriptureRef: 'Isaiah 53:5 (KJV)',
    narrative: 'Across centuries, God raised up prophets to prepare the world for the One who was coming. Isaiah described a Suffering Servant who would bear the sins of many and be "numbered with the transgressors." Daniel calculated a prophetic timeline, the seventy weeks, pointing to the exact period of the Messiah\'s anointing and sacrifice. Micah named the town of His birth. Zechariah described His betrayal for thirty pieces of silver. Psalm 22 detailed a crucifixion scene a thousand years before crucifixion was practised. These were not guesses. They were threads in a single tapestry, woven across generations by different writers who could not have coordinated their work, all converging on one person, one life, one redemptive act.',
    jesusConnection: 'Every thread met in Jesus of Nazareth. Born in Bethlehem (Micah 5:2). Baptised at the time Daniel foretold (Daniel 9:25). Entered Jerusalem on a donkey (Zechariah 9:9). Betrayed for thirty silver coins (Zechariah 11:12). Crucified alongside criminals (Isaiah 53:12). Not a bone broken (Psalm 34:20). Raised from the dead (Psalm 16:10). The mathematical probability of one person fulfilling even a handful of these prophecies by coincidence is beyond calculation. Jesus did not merely claim to be the Messiah. The entire Old Testament had already testified on His behalf.',
    jesusLabel: 'The Fulfilment of All Prophecy',
    color: '#b8c4d0',
    accentColor: '#8b2635',
  },
]

export default stories
