/**
 * THE SCARLET THREAD — Story Data
 * All 8 Old Testament chapters with scripture, narrative, and Jesus connections.
 * Content is Adventist-sensitive and educationally accurate.
 */

const stories = [
  {
    id: 'creation',
    chapter: 1,
    title: 'Creation',
    subtitle: 'In the Beginning',
    scripture: '"In the beginning God created the heavens and the earth. And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters. And God said, Let there be light: and there was light."',
    scriptureRef: 'Genesis 1:1–3 (KJV)',
    narrative: 'Before time, before matter, before light — there was God. From the infinite depths of His love, He spoke the universe into existence. Every star, every mountain, every living creature was crafted with intention. Humanity was made in His own image — not as servants, but as children. Creation was not an accident. It was a love letter, written in light.',
    jesusConnection: 'The Gospel of John reveals that Jesus was the Word through whom all things were made: "All things were made by him; and without him was not any thing made that was made" (John 1:3). The Creator would one day enter His own creation to redeem it.',
    jesusLabel: 'The Word Made Flesh',
    color: '#2a8a9e',
    accentColor: '#d4a843',
  },
  {
    id: 'the-fall',
    chapter: 2,
    title: 'The Fall & The Promise',
    subtitle: 'A Seed of Hope',
    scripture: '"And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel."',
    scriptureRef: 'Genesis 3:15 (KJV)',
    narrative: 'In the garden of Eden, humanity was given everything — and chose the one thing that was forbidden. Sin entered the world, and with it came death, separation, and sorrow. But even in that darkest moment, God did not abandon His children. He spoke the first prophecy — a promise that a Seed would come, born of a woman, who would crush the serpent\'s head. The wound would cost Him dearly, but victory was already decreed.',
    jesusConnection: 'This is the Protoevangelium — the first gospel. The "Seed of the woman" is Jesus Christ. He would be wounded on the cross ("bruise his heel"), but through His death and resurrection, He would destroy the power of sin and death forever ("bruise thy head").',
    jesusLabel: 'The First Gospel',
    color: '#8b6914',
    accentColor: '#d4a843',
  },
  {
    id: 'noah',
    chapter: 3,
    title: 'Noah & The Flood',
    subtitle: 'One Door, One Way',
    scripture: '"And the Lord said unto Noah, Come thou and all thy house into the ark; for thee have I seen righteous before me in this generation."',
    scriptureRef: 'Genesis 7:1 (KJV)',
    narrative: 'The world had grown so violent and corrupt that God\'s heart was grieved. Yet in the midst of universal rebellion, one man walked faithfully with God. Noah was told to build an ark — a vessel of salvation in a world that had never seen rain. For 120 years he preached and built, and the world laughed. Then the door closed, the rain fell, and only those inside the ark were saved. After the flood, God set a rainbow in the sky — a covenant of mercy that still arches over every storm.',
    jesusConnection: 'The ark had one door — and God Himself closed it. Jesus said, "I am the door: by me if any man enter in, he shall be saved" (John 10:9). Just as Noah\'s ark was the only refuge from judgment, Jesus is the only refuge from the consequences of sin. Peter connects the flood directly to baptism and salvation through Christ (1 Peter 3:20–21).',
    jesusLabel: 'The Door of Salvation',
    color: '#1a6b6b',
    accentColor: '#4ecdc4',
  },
  {
    id: 'abraham',
    chapter: 4,
    title: 'Abraham\'s Sacrifice',
    subtitle: 'God Will Provide',
    scripture: '"And Abraham said, My son, God will provide himself a lamb for a burnt offering."',
    scriptureRef: 'Genesis 22:8 (KJV)',
    narrative: 'God tested Abraham with an unimaginable request: offer your son, your only son, the son of promise, as a sacrifice on Mount Moriah. Abraham obeyed — not because he understood, but because he trusted. As the knife was raised, God intervened. A ram caught in a thicket became the substitute. Abraham named the place "The Lord Will Provide." The promise was preserved, and through Abraham\'s seed, all nations of the earth would be blessed.',
    jesusConnection: 'On that same mountain range — Mount Moriah, later called Calvary — God would not stay His hand. He offered His only Son, Jesus, as the Lamb of God. "For God so loved the world, that he gave his only begotten Son" (John 3:16). What Abraham was spared from doing, God did Himself. The ram in the thicket pointed forward to the Lamb who would take away the sin of the world.',
    jesusLabel: 'The Lamb of God',
    color: '#1a3a5c',
    accentColor: '#d4a843',
  },
  {
    id: 'exodus',
    chapter: 5,
    title: 'The Exodus & Passover',
    subtitle: 'The Blood of the Lamb',
    scripture: '"For even Christ our passover is sacrificed for us."',
    scriptureRef: '1 Corinthians 5:7 (KJV)',
    narrative: 'For 400 years, God\'s people suffered in Egyptian bondage. Then God raised up Moses and declared, "Let my people go." Through ten devastating plagues, Pharaoh\'s heart remained hard. The final plague — the death of the firstborn — would spare only those whose doorposts were marked with the blood of a spotless lamb. That night, the angel of death passed over every blood-marked door. Israel was set free, and God parted the Red Sea to make a way where there was no way.',
    jesusConnection: 'Paul declares plainly: "Christ our Passover is sacrificed for us." The spotless lamb, the blood on the doorposts, the deliverance from bondage — every detail of the Passover points to Jesus. His blood, shed on the cross, is what causes eternal death to "pass over" those who trust in Him. The parting of the sea shows that God makes a way of escape even when the situation seems impossible.',
    jesusLabel: 'Our Passover Lamb',
    color: '#c47a2a',
    accentColor: '#8b2635',
  },
  {
    id: 'sanctuary',
    chapter: 6,
    title: 'The Sanctuary',
    subtitle: 'A Shadow of Heavenly Things',
    scripture: '"And let them make me a sanctuary; that I may dwell among them."',
    scriptureRef: 'Exodus 25:8 (KJV)',
    narrative: 'God gave Moses detailed instructions for building the sanctuary — a sacred tent where heaven and earth could meet. Every element had meaning: the altar of sacrifice spoke of the cost of sin, the laver spoke of cleansing, the bread of the Presence spoke of God\'s sustenance, the lampstand spoke of His light, the incense spoke of prayer, and the Ark of the Covenant in the Most Holy Place spoke of God\'s very presence dwelling with His people. The High Priest entered the Most Holy Place once a year on the Day of Atonement, carrying blood to make atonement for the sins of the nation.',
    jesusConnection: 'The book of Hebrews reveals that the earthly sanctuary was "a shadow of heavenly things" (Hebrews 8:5). Jesus is the Lamb sacrificed at the altar. He is the Bread of Life, the Light of the World, and our great High Priest who "ever liveth to make intercession for us" (Hebrews 7:25). The veil that tore at His crucifixion (Matthew 27:51) opened the way into God\'s presence for all who believe.',
    jesusLabel: 'Our Great High Priest',
    color: '#4a2d6b',
    accentColor: '#d4a843',
  },
  {
    id: 'david',
    chapter: 7,
    title: 'David\'s Kingdom',
    subtitle: 'The Promised King',
    scripture: '"I am the root and the offspring of David, and the bright and morning star."',
    scriptureRef: 'Revelation 22:16 (KJV)',
    narrative: 'From a shepherd boy overlooked by his own family, God raised up a king after His own heart. David defeated giants, united a nation, and established Jerusalem as the city of God. Yet David was deeply flawed — a sinner saved by grace. God made David an extraordinary promise: his throne would be established forever. Not through David\'s perfection, but through the One who would come from his lineage — a King whose kingdom would have no end.',
    jesusConnection: 'Jesus is repeatedly called "the Son of David" throughout the Gospels. He was born in David\'s city (Bethlehem), from David\'s lineage, fulfilling the promise. But unlike David, Jesus is the sinless King. He came not to sit on an earthly throne, but to establish an eternal kingdom. The One who was greater than David chose to be born in a manger and crowned with thorns — the King who came as a servant.',
    jesusLabel: 'Son of David, King of Kings',
    color: '#1a3a5c',
    accentColor: '#d4a843',
  },
  {
    id: 'prophecy',
    chapter: 8,
    title: 'Prophetic Voices',
    subtitle: 'It Is Written',
    scripture: '"But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."',
    scriptureRef: 'Isaiah 53:5 (KJV)',
    narrative: 'For centuries, God sent prophets to prepare the world for the coming Messiah. Isaiah described a Suffering Servant who would bear the sins of many. Daniel calculated the exact timeline of the Messiah\'s arrival. Micah named the town of His birth — Bethlehem. Zechariah foretold He would be betrayed for thirty pieces of silver. Psalm 22 described the crucifixion a thousand years before it happened. Over 300 prophecies — written across centuries by different authors — all converged on one person.',
    jesusConnection: 'Every prophecy found its fulfillment in Jesus of Nazareth. Born in Bethlehem (Micah 5:2). Entered Jerusalem on a donkey (Zechariah 9:9). Betrayed for thirty pieces of silver (Zechariah 11:12–13). Crucified with criminals (Isaiah 53:12). Not a bone broken (Psalm 34:20). Rose from the dead (Psalm 16:10). The probability of one person fulfilling even a fraction of these prophecies by chance is beyond astronomical. Jesus didn\'t just claim to be the Messiah — the entire Old Testament testified of Him.',
    jesusLabel: 'The Fulfillment of All Prophecy',
    color: '#b8c4d0',
    accentColor: '#8b2635',
  },
]

export default stories
